version: 43.0.9
pageUuid: 84f2a654-a92e-11eb-a079-1bd02b8f4c2c
appTemplate:
  urlFragmentDefinitions: []
  appStyles: ''
  appThemeId: null
  preloadedAppJavaScript: null
  pageLoadValueOverrides: []
  customDocumentTitle: ''
  isGlobalWidget: false
  isFetching: false
  instrumentationEnabled: false
  customDocumentTitleEnabled: false
  preloadedAppJSLinks:
    array: []
  version: 2.66.90
  responsiveLayoutDisabled: false
  createdAt: null
  loadingIndicatorsDisabled: false
  testEntities:
    array:
      - object:
          id: eb62fa9e-074d-4925-8fb4-29b659e5697c
          name: test1
          body: assertCondition(true)
          type: test
          pauseAllQueries: true
          failureMessage: null
