version: 43.0.9
pageUuid: 84f2a654-a92e-11eb-a079-1bd02b8f4c2c
appTemplate:
  urlFragmentDefinitions: []
  appStyles: ''
  appThemeId: null
  preloadedAppJavaScript: null
  pageLoadValueOverrides: []
  customDocumentTitle: ''
  isGlobalWidget: false
  isFetching: false
  instrumentationEnabled: false
  customDocumentTitleEnabled: false
  preloadedAppJSLinks:
    array: []
  version: 2.66.90
  responsiveLayoutDisabled: false
  createdAt: null
  loadingIndicatorsDisabled: false
